### PR TITLE
Swift example

### PR DESCRIPTION
**Pull request by hfossli**

### CODE REVIEW

**Comment by hfossli** [comment]
(these commits can (should) be squashed)

**Comment by hfossli** [comment]
Any reason for this taking so long? I am in fact considering closing this pull request and withdrawing my offer to contribute to this repo. I don't see myself creating new pull requests taking months to fulfill or even get feedback on. If things are to change then I'm here to stay, but if you're just pressing "merge" I don't see that as a meaningful conversation taking place. Just being honest. Let me know what you think.

**Comment by withzombies** [comment]
Sorry, we've been busy. I'll be able to get to it next week.

**Comment by withzombies** [comment]
Sorry this took so long. This looks good, I just have one request: could you explicitly specify the Apache2 license in the following files:

* ./SecureEnclaveDemo/AppDelegate.swift
* ./SecureEnclaveDemo/Manager.swift
* ./SecureEnclaveDemo/ViewController.swift
* ./SecureEnclaveDemoTests/SecureEnclaveDemoTests.swift

Right now they're marked as "All Rights Reserved.", which prevents them from being used as open source libraries. Once those are updated, I'll accept the merge and update the README.

**Comment by withzombies** [comment]
Thanks @hfossli. Sorry about the delay.

**Comment by hfossli** [comment]
Awesome. I guess I'll be reviewing future pull requests and issue tracking regarding the swift code. Would be cool to join this repo as a contributor with write access in that sense.

**Comment by hfossli** [comment]
Cool! 👍🎉

**Pull request merged**
